export const strings = {
  home: "Home",
  services: "Services",
  portfolio: "Portfolio",
  aboutUs: "About Us",
  blogs: "Blogs",
  careers: "Careers",
  awards: "Awards",
  getInTouch: "Get in Touch",
  calculateCost: "Calculate Project Cost",
  excellenceBtn: "A trusted place where Innovation meets Excellence",
  heroTitle: "Driving startup success with tailored digital solutions: from mobile and web apps to AI-powered innovations.",
  heroDescription: "We specialize in designing and developing scalable web and mobile applications,",
  heroDescription2: "custom-tailored to meet the unique needs and challenges of your business.",
  heroBtn1: "View Our Services",
  heroBtn2: "Let's Talk",
  serviceDetailsBtn: "Our Services",
  serviceBtn: "Services",
  allServicesBtn: "View all Our Services",
  serviceTitle: "Services we provide",
  bannerTitle: "Project Cost Calculator",
  bannerHeading: "Have a project idea in mind?",
  bannerDesc: "Find out how much it costs to build such an app and how long it takes to launch it.",
  bannerBtn: "Estimate your project cost",
  learnMore: "Learn About Us",
  whyUs: "Why Us",
  aboutTitle: "Building software for global leaders.",
  aboutDescription:
    "At Exeonic, we're dedicated to harnessing the power of AI and custom software development to drive business transformation. With over seven years of experience, we specialize in delivering innovative and tailored solutions that leverage the latest technologies to streamline operations, boost efficiency, and foster growth.",
  ourAwardsAndCertificates: "Our Awards & Certificates",
  partnerWithUsNow: "Partner With Us Now",
  partnerTitle: "Ready to Build Innovative Solutions for Your Business?",
  partnerDescription:
    "Partner with us to transform your ideas into robust, scalable solutions that drive growth and innovation. Our dedicated team will work closely with you to ensure every aspect of your project is aligned with your business goals.",
  getStarted: "Get Started Now",
  footerDescription: "We specialize in designing and developing scalable web and mobile applications, custom-tailored to meet the unique needs and challenges of your business.",
  newsLetTitle: "Subscribe to our newsletter",
  newsLetterDesc: "Join our newsletter to stay updated about our latest news and articles.",
  copyRight: "Copyright ©️ 2024 Exeonic. All rights reserved.",
  whyChooseUs: "Why Exeonic Solutions?",
  maintainance: "Site is under maintenance!",
  maintainMsg: "We are extremely sorry for inconvenience. We will be back soon live!",
  error: "No Page Found!",
  joinUs: "Join Us!",
  testimonialTitle: "Testimonials",
  testimonialHeading: "Don’t just take our word for it",
  testimonialDesc: "Discover how our products and services have helped businesses like yours achieve their goals.",
  contactTitle: "Contact Us",
  contactHeading: "Send a message to get your free quote",
  contactDesc: "Curious about how we can bring your vision to life? Let's discuss your project in detail.",
  email: "Email Us",
  companyMail: "hello@exeonic.com",
  contact: "Contact Us",
  companyContact: "+92 317 4922289",
  nameInput: "Full Name",
  emailInput: "Email Address",
  messageInput: "Message",
  checkInput: "I’d like to occasionally receive other communication from Exeonic, such as contact and product news",
  contactBtn: "Submit",
  designer: "UI/UX DESIGNER",
  jobDescrip:
    "From concept to launch, we handle every stage of the development process, ensuring a seamless and efficient experience. Our apps are designed to engage, inform, and entertain,providing a valuable experience for your customers. Let us help you reach new heights with a cutting-edge mobile app that sets you apart from the competition!",
  jobDescTitle: "Job Description",
  intrested: "Apply",
  apply: "Apply Now",
  uploadCV: "Upload CV",
  fileAttachment: "No file chosen",
  findUs: "Where to Find Us?",
  locations: "Locations",
  faqTitle: "FAQs",
  faqHeading: "Frequently Asked Questions",
  faqDesc: "This is where we answer all your questions. Check it out.",
  faqHeading2: "You have different questions?",
  faqDesc2: "Our team will answer all your quesions.",
  faqDesc3: "We ensure a quick response.",
  faqBtn: "Contact Support team",
  launchTitle: "Launch in 6 weeks",
  launchHeading: "Accelerate Your Startup Growth",
  launchDesc: "We will finalize the prototype into a functional product in just 4 Weeks and release the product on public stores for users in 6 Weeks.",
  servicesHeader: "SERVICE WE PROVIDE",
  portfolioHeader: "BRINGING VISION TO LIFE",
  blogsHeader: "BLOGS & ARTICLES",
  liveSection: "View live project",
  blogsTitle: "Blogs & Articles",
  blogsHeading: "Resources to help you to grow your business",
  blogsBtn: "View more blogs",
  termsAndConditions: "TERM & CONDITIONS",
  privacyPolicy: "PRIVACY POLICY",
  getDirection: "Get Directions",
  achievementTitle: "Achievements",
  achievementHeading: "Our achievements in numbers",
  blogsCardTitle: "Artificial Intelligence",
  blogDesc: "Mastering ChatGPT Blog Creation: Dos and Don'ts for SaaS Marketing Managers",
  blogDate: "October 19",
  blogTime: "10 min ago",
  artical: "In this article",
  relatedArticals: "Related Articles",
  successMsg: "Successfully Submitted",
  successDescription: "Your information is submitted successfully. We will get back to you shortly through an Email",
  goToHome: "Return to home",
  loadArticals: " Load More Articals",
  viewAllBlogs: "View All Blogs",
  applyNow: "Apply Now",
  disclaimer: "I agree to work in the Faisalabad office from 10 AM to 7 PM, Monday to Saturday.",
};
